### ISSUE TITLE
Reply vanishes when editing existing comment (was: Possible bug)

### ISSUE THREAD

**Issue by dnoneill** [recogito/recogito-client-core#37] opened 2020-11-30 21:37 UTC
See attached gif

![ezgif-6-4fd91a4080e3](https://user-images.githubusercontent.com/19173991/100668726-39ac8400-3311-11eb-90d5-8b93ba06550d.gif)

**Comment by rsimon** [comment] 2020-12-01 07:01
Yes, that's a known issue, but didn't have a Github ticket yet. Thx for creating. It's a bit of a tricky "artefact" from the way the implementation maps WebAnno bodies to the editor state in React. (All the bodies correspond to controlled React components. The thing that causes problems conceptually is the reply: there needs to be a component for it, but it shouldn't exist as an annotation body, as long as it's empty. You may have seen the "draft" property in the code. That's the hack I introduced to have a "fake body" in the state. Now the problem is: once a comment is edited, it goes draft and I don't have a way to track which draft comment is which... In short: the whole thing needs a bit of a redesign internally. I think the key will be to **not** implement this in a React-controlled-component way, but more conventional. But need time to think this through...)

**Comment by rsimon** [comment] 2020-12-20 20:40
Relates to https://github.com/recogito/recogito-client-core/issues/42

**Comment by rsimon** [comment] 2020-12-21 12:39
This is now resolved in the master branch, and will go live with the next release.

**Closed by rsimon** 2020-12-21 12:39 UTC
