### ISSUE TITLE
error finding type on custom widget

### ISSUE THREAD

**Issue by bmschmidt** [recogito/recogito-client-core#93] opened 2021-11-23 22:38 UTC
Thanks for all your work on this great library.

I'm in no way confident the problem I'm seeing here is a bug, but it's a little long to post on gitter.

I'm trying to generate my own widgets in vanilla js using the model at [https://recogito.github.io/guides/editor-widgets], which I've abstracted into a general factory so I can add some mutually exclusive classification buttons. I can get it to work and create annotations correctly; but when I attempt to click on the annotation again to change it, the annotation breaks when a check is done for `w.type.disableDelete` [in this code block](https://github.com/recogito/recogito-client-core/blob/4e2b681bed01f6fb675a0da2f8a5eacb7aff8083/src/editor/Editor.jsx#L301-L306) because `w.type` is not defined.

It's not clear to what object I could add some dummy property `{type: {disableDelete: false}}`. Any hints?

Thanks!

For the record, my factory function is below.

```js



export default function button_widget_factory(class_name : string, fields: string[]) {
  // creates a widget
  return function my_widget(args) {

    // a special identifier code for changing all of them at once.
    // 1. Find a current color setting in the annotation, if any
    const currentValue = args.annotation ? 
      args.annotation.bodies.find(function(b) {
        return b.purpose == 'tagging' && b.value && b.value.startsWith(class_name + ": ");
      }) : null;

    // 2. Keep the value in a variable
    const currentTagValue = currentValue ? currentValue.value : null;

    // 3. Triggers callbacks on user action
    const addTag = function(evt) {
      if (currentValue) {
        args.onUpdateBody(currentValue, {
          type: 'TextualBody',
          purpose: 'tagging',
          value: evt.target.dataset.tag
        });
      } else { 
        args.onAppendBody({
          type: 'TextualBody',
          purpose: 'tagging',
          value: evt.target.dataset.tag
        });
      }
    }

    // 4. This part renders the UI elements
    const createButton = function(value) {
      const button = document.createElement('button');
      // IBM carbon classes added as well as the group code.
      const full_name = class_name + ": " + value;
      button.className = 
      `bx--btn bx--btn--${full_name === currentTagValue ? "primary" : "secondary"}`;

      button.innerText = value;
      button.dataset.tag = full_name;
      button.addEventListener('click', addTag); 
      return button;
    }

    const container = document.createElement('div');
    container.className = class_name;
    
    for (const k of fields) {
      const button = createButton(k);
      container.appendChild(button);
    }
    return container;
  }
}

```

**Comment by rsimon** [comment] 2021-11-24 06:42
Update: transferred this issue to the `recogito-client-core` repo, since it's caused by a bug there.

**Comment by bmschmidt** [comment] 2021-11-24 14:43
Thanks for looking into this. I've realized that for my purposes what I wanted to avoid was having to write any jsx files, but I forgot that I could still write react components without them and that preact is already in the bundle anyway. So feel no need to work on this on my account.

**Comment by bmschmidt** [comment] 2021-11-24 15:19
Actually, I seem to encounter this problem with a custom react widget as well. I thought I could follow the comment widget model as a workaround and bind something to disableDelete, but this seems not to work for reasons that--not really understanding React--are opaque to me.

```js
const widget = props => {
  [etc]
  return /*#__PURE__*/React.createElement("div",
  [etc]
}
widget.disableDelete = () => false
return widget;
}

**Comment by rsimon** [comment] 2021-11-25 06:53
Hi again, 

I checked and actually this seems to work ok, both for Vanilla JS and React-based widgets. So I'm suspecting it might be something specific to your widget. Can you post a code snippet for the widget and/or how you are initializing it with Annotorious?

**Comment by bmschmidt** [comment] 2021-11-29 15:44
Sorry for the delay, holiday over here.

Thanks for your help, I think you're right and that this is all my fault. Feel free to close. Experimenting I find it does work *if* I also include the native tagging widget. So it seems possibly problem here is that I was trying to add multiple components that each overwrote the goals for 'purpose': 'tagging', ignoring your instructions online that each widget should own a single purpose.

I haven't explored behavior if I try to create just one 'purpose: tagging' widget of my own, because I've switched to a slightly different model for now in which I generate tags/classifications in different part of the DOM and use annotorious for drawing but not tag generation.

**Closed** 2021-12-03 11:51 UTC
